travis:
  secure:
    BINSTAR_TOKEN: pjKGYirIpf21cp5yS1RphS0XsUz89DAecvetiS0acQovS8KEXjDh5/QlqgF/qnLT7Tt84vIA3MYqusKtUKETcJ5pWM62d19O35B45CFyOG9qHfE5z7qhs/I7LytlVzZpzJCJqowj9osZvo/rslYAuFTun0jmi5SO4KouNrT09kJXpvAKunJswToGHrhqOmyjE04HuGpTNG4G+wUf62Z2IkWduDkPOu/yGiqwE1OfycwDp9Q4RIbKCB7xuLcEPr6/Cx2YMG+5K5o4ulClJze/Go1yRCMzwUjmiHiN974YITPyGVC/5YGjf1C4OnJJcONnKRDJKRJiWqtlGb+rmPZo36BiDuZeuWn01wemTHkmFKP1KXIhS/xAZX/0Sn9Z3YYaIwEJp9Foyh3dGJLbdeXWWeUZz57XZjMp3cVWxm7d809KevRUBjppiFDGPe1zztzKQrcNiBDrhJI+G3wfR8A6Mjftgd9uDn6FCrqGFEu0owV3IcVcINWKA+YTEm5w9GaYl2BIw8tcItnKjNEDnNgAioZpFVX7Zk4hF5jsu7lbTTim8tMcr7QNS5QtwqtzlONvqEKkhoHa0d/6GCGcQTBhevmptThZawkLt633q/zwIUYQJi/6qPXgicNBuGvO61QW4d+4tS8n389qMn5br0POvEBy/N7kBn0wwtUPxSyAXMc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
